print('=ˆ= ' * 8)
print('    TAULA DE MULTIPLICACIÓ')
print('=ˆ= ' * 8)
num = int(input('introduïu un número per trobar\nla taula de multiplicació: '))
print(' ' * 7, '-' * 13)
print(' ' * 7, '{} x {:2} = {:3}'.format(num, 1, num * 1))
print(' ' * 7, '{} x {:2} = {:3}'.format(num, 2, num * 2))
print(' ' * 7, '{} x {:2} = {:3}'.format(num, 3, num * 3))
print(' ' * 7, '{} x {:2} = {:3}'.format(num, 4, num * 4))
print(' ' * 7, '{} x {:2} = {:3}'.format(num, 5, num * 5))
print(' ' * 7, '{} x {:2} = {:3}'.format(num, 6, num * 6))
print(' ' * 7, '{} x {:2} = {:3}'.format(num, 7, num * 7))
print(' ' * 7, '{} x {:2} = {:3}'.format(num, 8, num * 8))
print(' ' * 7, '{} x {:2} = {:3}'.format(num, 9, num * 9))
print(' ' * 7, '{} x {:2} = {:3}'.format(num, 10, num * 10))
print(' ' * 7, '-' * 13)
