print('=ˆ= ' * 11)
print('             analitzant noms')
print('=ˆ= ' * 11)
nom = str(input('com es diu? ')).strip()
print('el teu nom en majúscules és {}'.format(nom.upper()))
print('el teu nom en minúscules é {}'.format(nom.lower()))
print('el teu nome té {} lletres'.format(len(nom) - nom.count(' ')))
dividit = nom.split()
print('el teu primer nom és {} i té {} lletres'.format(dividit[0], len(dividit[0])))