x = input('escriu alguna cosa: ')
print('el tipus primitiu d’aquest valor és', type(x))
print('el que heu escrit només té espais?', x.isspace())
print('el que heu escrit és numèric?', x.isnumeric())
print('el que heu escrit és alfabètic?', x.isalpha())
print('el que heu escrit és alfanumèric?', x.isalnum())
print('és el que heu escrit amb majúscules?', x.isupper())
print('és el que heu escrit amb minúscules?', x.islower())
print('el que heu escrit amb la primera lletra majúscula?', x.istitle())